-- Atualização V2: execute este arquivo inteiro, uma vez, no SQL Editor.
-- Compatível com o projeto original e com a migração diária anterior.
-- Não execute novamente supabase-schema.sql. Não apaga registros existentes.
begin;
lock table public.sample_records in share row exclusive mode;
create table if not exists public.daily_records (
 id bigint generated by default as identity primary key,
 coordinator text not null default '', leader text not null default '',
 record_date date not null,
 confirmed integer not null default 0 check (confirmed >= 0),
 not_confirmed integer not null default 0 check (not_confirmed >= 0),
 does_not_know integer not null default 0 check (does_not_know >= 0),
 mailbox integer not null default 0 check (mailbox >= 0),
 notes text not null default '',
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
lock table public.daily_records in share row exclusive mode;
alter table public.daily_records add column if not exists record_id bigint references public.sample_records(id) on delete cascade;
alter table public.sample_records add column if not exists record_date date not null default date '2026-09-11';
-- Conecta lançamentos da versão anterior somente quando a correspondência é única.
do $$
begin
 if exists (
  select 1 from public.daily_records d where d.record_id is null
  and (select count(*) from public.sample_records s where s.coordinator=d.coordinator and s.leader=d.leader) <> 1
 ) then
  raise exception 'Há nomes sem correspondência única entre bases e lançamentos. Nenhuma alteração foi aplicada. Revise as duplicidades antes de continuar.';
 end if;
end $$;
update public.daily_records d set record_id=s.id
from public.sample_records s where d.record_id is null and d.coordinator=s.coordinator and d.leader=s.leader;
-- Importa cada base sem histórico uma única vez. Os testes ficam em 11/09/2026.
insert into public.daily_records(record_id,coordinator,leader,record_date,confirmed,not_confirmed,does_not_know,mailbox,notes)
select s.id,s.coordinator,s.leader,date '2026-09-11',s.confirmed,s.not_confirmed,s.does_not_know,s.mailbox,'Registro existente preservado em 11/09/2026.'
from public.sample_records s where not exists(select 1 from public.daily_records d where d.record_id=s.id);
alter table public.daily_records alter column record_id set not null;
create index if not exists daily_record_date_v2 on public.daily_records(record_id,record_date,id);
alter table public.daily_records enable row level security;
drop policy if exists "authenticated read daily records" on public.daily_records;
drop policy if exists "authenticated add daily records" on public.daily_records;
drop policy if exists "authenticated edit daily records" on public.daily_records;
drop policy if exists "admin delete daily records" on public.daily_records;
create policy "authenticated read daily records" on public.daily_records for select to authenticated using (true);
create policy "authenticated add daily records" on public.daily_records for insert to authenticated with check (true);
create policy "authenticated edit daily records" on public.daily_records for update to authenticated using (true) with check (true);
create policy "admin delete daily records" on public.daily_records for delete to authenticated using (public.is_admin());
grant select,insert,update,delete on public.daily_records to authenticated;
grant usage,select on sequence public.daily_records_id_seq to authenticated;
-- Reconcilia acumulados com todo o histórico sem somar a base novamente.
update public.sample_records s set
 confirmed=t.confirmed,not_confirmed=t.not_confirmed,does_not_know=t.does_not_know,mailbox=t.mailbox,record_date=t.first_date
from (select record_id,sum(confirmed)::integer confirmed,sum(not_confirmed)::integer not_confirmed,
sum(does_not_know)::integer does_not_know,sum(mailbox)::integer mailbox,min(record_date) first_date
from public.daily_records group by record_id) t where s.id=t.record_id;

-- A trava por base evita que dois lançamentos simultâneos ultrapassem o saldo.
create or replace function public.validate_daily_v2()
returns trigger language plpgsql security definer set search_path=public as $$
declare b public.sample_records; previous bigint;
begin
 if TG_OP='UPDATE' and new.record_id<>old.record_id then raise exception 'Não é possível transferir o lançamento para outra base.'; end if;
 select * into b from public.sample_records where id=new.record_id for update;
 if not found then raise exception 'Base não encontrada.'; end if;
 if new.record_date is null or new.record_date>(now() at time zone 'America/Manaus')::date then raise exception 'Informe uma data válida, até hoje.'; end if;
 if new.confirmed<0 or new.not_confirmed<0 or new.does_not_know<0 or new.mailbox<0 then raise exception 'Use inteiros não negativos.'; end if;
 select coalesce(sum(d.confirmed::bigint+d.not_confirmed+d.does_not_know+d.mailbox),0) into previous
 from public.daily_records d where d.record_id=new.record_id and (TG_OP='INSERT' or d.id<>new.id);
 if previous+new.confirmed::bigint+new.not_confirmed+new.does_not_know+new.mailbox>b.total_base then raise exception 'O lançamento ultrapassa o saldo pendente da base. Atualize os dados.'; end if;
 new.coordinator=b.coordinator;new.leader=b.leader;new.updated_at=now();
 return new;
end $$;
create or replace function public.sync_daily_v2()
returns trigger language plpgsql security definer set search_path=public as $$
declare target bigint;
begin
 target=case when TG_OP='DELETE' then old.record_id else new.record_id end;
 perform 1 from public.sample_records where id=target for update;
 update public.sample_records s set
 confirmed=t.c,not_confirmed=t.n,does_not_know=t.d,mailbox=t.m,updated_at=now()
 from (select coalesce(sum(confirmed),0)::integer c,coalesce(sum(not_confirmed),0)::integer n,
 coalesce(sum(does_not_know),0)::integer d,coalesce(sum(mailbox),0)::integer m from public.daily_records where record_id=target) t
 where s.id=target;
 return null;
end $$;
drop trigger if exists daily_validate_v2 on public.daily_records;
create trigger daily_validate_v2 before insert or update on public.daily_records for each row execute function public.validate_daily_v2();
drop trigger if exists daily_sync_v2 on public.daily_records;
create trigger daily_sync_v2 after insert or update or delete on public.daily_records for each row execute function public.sync_daily_v2();

-- Cadastro inicial + primeiro lançamento são gravados na mesma transação.
create or replace function public.save_sampling_base_v2(p_id bigint,p_values jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare b public.sample_records; target bigint; day date; c integer; n integer; d integer; m integer; base integer;
begin
 if auth.uid() is null then raise exception 'Entre na sua conta para salvar.'; end if;
 if trim(coalesce(p_values->>'coordinator',''))='' or trim(coalesce(p_values->>'leader',''))='' then raise exception 'Preencha coordenador e líder.'; end if;
 base=(p_values->>'total_base')::integer;
 if base is null or base<0 then raise exception 'Informe uma base válida.'; end if;
 if p_id is null then
  perform pg_advisory_xact_lock(hashtextextended(trim(p_values->>'coordinator')||chr(31)||trim(p_values->>'leader'),0));
  if exists(select 1 from public.sample_records where coordinator=trim(p_values->>'coordinator') and leader=trim(p_values->>'leader')) then
   raise exception 'Este líder já tem uma base neste coordenador. Use Registros diários para acrescentar a produção.';
  end if;
  c=coalesce((p_values->>'confirmed')::integer,0);n=coalesce((p_values->>'not_confirmed')::integer,0);
  d=coalesce((p_values->>'does_not_know')::integer,0);m=coalesce((p_values->>'mailbox')::integer,0);
  day=(p_values->>'record_date')::date;
  if day is null then raise exception 'Informe a data do registro.'; end if;
  insert into public.sample_records(coordinator,leader,total_base,record_date)
  values(trim(p_values->>'coordinator'),trim(p_values->>'leader'),base,day) returning id into target;
  insert into public.daily_records(record_id,record_date,confirmed,not_confirmed,does_not_know,mailbox)
  values(target,day,c,n,d,m);
 else
  target=p_id;
  select * into b from public.sample_records where id=target for update;
  if not found then raise exception 'Registro não encontrado.'; end if;
  if base<b.confirmed::bigint+b.not_confirmed+b.does_not_know+b.mailbox then raise exception 'A base não pode ser menor que os contatos acumulados.'; end if;
  update public.sample_records set coordinator=trim(p_values->>'coordinator'),leader=trim(p_values->>'leader'),total_base=base,updated_at=now() where id=target;
 end if;
 select * into b from public.sample_records where id=target;
 return to_jsonb(b);
end $$;
revoke all on function public.save_sampling_base_v2(bigint,jsonb) from public,anon;
grant execute on function public.save_sampling_base_v2(bigint,jsonb) to authenticated;
commit;
