(() => {
  const cfg = window.APP_CONFIG || {}; if (!cfg.SUPABASE_URL || cfg.SUPABASE_URL.includes('COLE_AQUI')) { location.replace('login.html'); return; }
  const db = window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY), fields = ['coordinator','leader','total_base','confirmed','not_confirmed','does_not_know','mailbox'], numeric = new Set(fields.slice(2));
  let records = [], selected = 'ALL', admin = false, chart;
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const contacted = r => (+r.confirmed||0)+(+r.not_confirmed||0)+(+r.does_not_know||0)+(+r.mailbox||0);
  const rate = r => contacted(r) ? (+r.confirmed||0)*100/contacted(r) : 0;
  const shown = () => selected === 'ALL' ? records : records.filter(r => r.coordinator === selected);
  async function start() {
    const {data:{session}} = await db.auth.getSession(); if (!session) { location.replace('login.html'); return; }
    const {data:p,error} = await db.from('profiles').select('display_name,role').single(); if (error) { alert('Não foi possível carregar seu perfil: '+error.message); return; }
    admin = p.role === 'admin'; document.querySelector('#user-name').textContent = p.display_name; document.querySelector('#role-badge').textContent = admin ? 'Administrador' : 'Usuário';
    document.querySelector('#logout').onclick = async () => { await db.auth.signOut(); location.replace('login.html'); };
    document.querySelector('#add').onclick = add; document.querySelector('#filter').onchange = e => { selected=e.target.value; render(); }; await load();
  }
  async function load() { const {data,error}=await db.from('sample_records').select('*').order('id'); if(error) return alert('Erro ao carregar: '+error.message); records=data; render(); }
  function render() {
    const data=shown(), select=document.querySelector('#filter'), names=[...new Set(records.map(r=>r.coordinator).filter(Boolean))].sort((a,b)=>a.localeCompare(b));
    if(!names.includes(selected)) selected='ALL'; select.innerHTML=`<option value="ALL">Todos os coordenadores</option>${names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('')}`; select.value=selected;
    document.querySelector('#info').textContent=`${data.length} registro${data.length===1?'':'s'} exibido${data.length===1?'':'s'}`; rows(data); cards(data); ranking(data); graph(data); lucide.createIcons();
  }
  function rows(data) {
    document.querySelector('#rows').innerHTML=data.map(r=>`<tr data-id="${r.id}">${fields.map(f=>`<td><input class="cell" data-field="${f}" ${numeric.has(f)?'type="number" min="0"':''} value="${esc(r[f])}"></td>`).join('')}<td class="font-bold text-indigo-600">${contacted(r)}</td><td class="font-bold">${rate(r).toFixed(1).replace('.',',')}%</td><td>${admin?'<button data-delete class="text-rose-600 font-semibold">Excluir</button>':'—'}</td></tr>`).join('');
    document.querySelectorAll('#rows input').forEach(i=>i.onchange=save); document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(+b.closest('tr').dataset.id));
    const t=data.reduce((a,r)=>({total_base:a.total_base+(+r.total_base||0),confirmed:a.confirmed+(+r.confirmed||0),not_confirmed:a.not_confirmed+(+r.not_confirmed||0),does_not_know:a.does_not_know+(+r.does_not_know||0),mailbox:a.mailbox+(+r.mailbox||0)}),{total_base:0,confirmed:0,not_confirmed:0,does_not_know:0,mailbox:0});
    document.querySelector('#totals').innerHTML=`<tr class="bg-slate-50 font-bold"><td colspan="2">Consolidado</td><td>${t.total_base}</td><td>${t.confirmed}</td><td>${t.not_confirmed}</td><td>${t.does_not_know}</td><td>${t.mailbox}</td><td>${contacted(t)}</td><td>${rate(t).toFixed(1).replace('.',',')}%</td><td></td></tr>`;
  }
  function cards(data) { const groups={}; data.forEach(r=>(groups[r.coordinator||'Sem coordenador']??=[]).push(r)); document.querySelector('#cards').innerHTML=Object.entries(groups).map(([n,list])=>{const base=list.reduce((x,r)=>x+(+r.total_base||0),0), c=list.reduce((x,r)=>x+contacted(r),0), ok=list.reduce((x,r)=>x+(+r.confirmed||0),0), s=base?c*100/base:0; return `<article class="card p-5"><div class="flex justify-between"><div><h3 class="font-bold">${esc(n)}</h3><p class="text-xs text-slate-500">${list.length} líder(es)</p></div><span class="badge">${c?(ok*100/c).toFixed(1).replace('.',','):'0,0'}%</span></div><p class="mt-4 text-sm">Amostragem: <strong>${c} / ${base}</strong> (${s.toFixed(0)}%)</p><div class="mt-2 h-2 rounded-full bg-slate-100"><div class="h-full bg-blue-600" style="width:${Math.min(s,100)}%"></div></div></article>`;}).join('')||'<p class="text-slate-500">Nenhum registro.</p>'; }
  function ranking(data) { document.querySelector('#ranking').innerHTML=[...data].sort((a,b)=>rate(b)-rate(a)).map((r,i)=>`<div class="flex justify-between rounded-xl bg-slate-50 p-3"><span><strong class="mr-2 text-blue-600">${i+1}º</strong>${esc(r.leader)}</span><strong>${rate(r).toFixed(1).replace('.',',')}%</strong></div>`).join('')||'<p class="text-sm text-slate-500">Sem dados.</p>'; }
  function graph(data) { if(chart)chart.destroy(); chart=new Chart(document.querySelector('#chart'),{type:'bar',data:{labels:data.map(r=>r.leader),datasets:[{data:data.map(rate),backgroundColor:'#2563eb',borderRadius:6}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,max:100,ticks:{callback:v=>v+'%'}},x:{grid:{display:false}}}}}); }
  async function save(e) { const id=+e.target.closest('tr').dataset.id, field=e.target.dataset.field, value=numeric.has(field)?Math.max(0,Number(e.target.value)||0):e.target.value.trim(), {error}=await db.from('sample_records').update({[field]:value,updated_at:new Date().toISOString()}).eq('id',id); if(error){alert('Não foi possível salvar: '+error.message);return load();} Object.assign(records.find(r=>r.id===id),{[field]:value});render(); }
  async function add(){const {data,error}=await db.from('sample_records').insert({coordinator:selected==='ALL'?'Novo Coordenador':selected,leader:'Novo Líder'}).select().single();if(error)return alert(error.message);records.push(data);render();}
  async function remove(id){if(!confirm('Excluir este registro?'))return;const {error}=await db.from('sample_records').delete().eq('id',id);if(error)return alert('Apenas o administrador pode excluir.');records=records.filter(r=>r.id!==id);render();}
  const stamp=()=>new Date().toISOString().slice(0,10), download=(s,n,t)=>{const u=URL.createObjectURL(new Blob([s],{type:t})),a=document.createElement('a');a.href=u;a.download=n;a.click();URL.revokeObjectURL(u);}, exportRows=data=>data.map(r=>({'Coordenador':r.coordinator||'','Líder':r.leader||'','Total Base':+r.total_base||0,'Confirmado':+r.confirmed||0,'Não Confirmado':+r.not_confirmed||0,'Não Conhece Líder':+r.does_not_know||0,'Caixa Postal':+r.mailbox||0,'Contatadas':contacted(r),'% Confirmação':`${rate(r).toFixed(1)}%`}));
  window.salvarExcel=()=>{const b=XLSX.utils.book_new();XLSX.utils.book_append_sheet(b,XLSX.utils.json_to_sheet(exportRows(shown())),'Matriz Qualidade');XLSX.writeFile(b,`qualidade_matriz_${stamp()}.xlsx`);};
  window.baixarResumoDoDiaExcel=()=>{const b=XLSX.utils.book_new(),base=records.reduce((n,r)=>n+(+r.total_base||0),0),c=records.reduce((n,r)=>n+contacted(r),0),ok=records.reduce((n,r)=>n+(+r.confirmed||0),0);XLSX.utils.book_append_sheet(b,XLSX.utils.json_to_sheet([{'Métrica':'Data do relatório','Valor':new Date().toLocaleDateString('pt-BR')},{'Métrica':'Total Base','Valor':base},{'Métrica':'Pessoas contatadas','Valor':c},{'Métrica':'Taxa de confirmação','Valor':`${c?(ok*100/c).toFixed(1):'0.0'}%`}]),'Resumo Executivo');XLSX.utils.book_append_sheet(b,XLSX.utils.json_to_sheet(exportRows(records)),'Detalhamento');XLSX.writeFile(b,`resumo_diario_qualidade_${stamp()}.xlsx`);};
  window.exportarBackupJSON=()=>download(JSON.stringify(records,null,2),`backup_amostragem_${stamp()}.json`,'application/json;charset=utf-8');
  window.exportarXML=()=>{const x=['<?xml version="1.0" encoding="UTF-8"?>','<relatorio_qualidade>',...shown().map(r=>`<item><id>${r.id}</id><coordenador>${esc(r.coordinator)}</coordenador><lider>${esc(r.leader)}</lider><total>${r.total_base}</total><confirmado>${r.confirmed}</confirmado></item>`),'</relatorio_qualidade>'].join('\n');download(x,`relatorio_qualidade_${stamp()}.xml`,'application/xml;charset=utf-8');};
  start();
})();
