-- Execute uma vez no SQL Editor do Supabase do projeto já publicado.
-- Cria o histórico por data e preserva os testes existentes como produção de 11/09/2026.
create table if not exists public.daily_records (
  id bigint generated by default as identity primary key,
  coordinator text not null default '', leader text not null default '', record_date date not null,
  confirmed integer not null default 0 check (confirmed >= 0),
  not_confirmed integer not null default 0 check (not_confirmed >= 0),
  does_not_know integer not null default 0 check (does_not_know >= 0),
  mailbox integer not null default 0 check (mailbox >= 0), notes text not null default '',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.daily_records enable row level security;
drop policy if exists "authenticated read daily records" on public.daily_records;
drop policy if exists "authenticated add daily records" on public.daily_records;
drop policy if exists "authenticated edit daily records" on public.daily_records;
drop policy if exists "admin delete daily records" on public.daily_records;
create policy "authenticated read daily records" on public.daily_records for select to authenticated using (true);
create policy "authenticated add daily records" on public.daily_records for insert to authenticated with check (true);
create policy "authenticated edit daily records" on public.daily_records for update to authenticated using (true) with check (true);
create policy "admin delete daily records" on public.daily_records for delete to authenticated using (public.is_admin());
insert into public.daily_records
  (coordinator, leader, record_date, confirmed, not_confirmed, does_not_know, mailbox, notes)
select coordinator, leader, date '2026-09-11', confirmed, not_confirmed, does_not_know, mailbox,
       'Registro existente migrado para o histórico diário.'
from public.sample_records
where not exists (select 1 from public.daily_records);
