-- Execute este arquivo no SQL Editor do Supabase antes de criar os usuarios.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Usuário',
  role text not null default 'user' check (role in ('admin', 'user')),
  created_at timestamptz not null default now()
);

create table if not exists public.sample_records (
  id bigint generated by default as identity primary key,
  coordinator text not null default '', leader text not null default '',
  total_base integer not null default 0 check (total_base >= 0),
  confirmed integer not null default 0 check (confirmed >= 0),
  not_confirmed integer not null default 0 check (not_confirmed >= 0),
  does_not_know integer not null default 0 check (does_not_know >= 0),
  mailbox integer not null default 0 check (mailbox >= 0),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.sample_records enable row level security;

create or replace function public.create_profile()
returns trigger language plpgsql security definer set search_path = public as $$
begin insert into public.profiles (id, display_name) values (new.id, coalesce(new.raw_user_meta_data->>'display_name', 'Usuário')); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.create_profile();

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create policy "profile own read" on public.profiles for select to authenticated using (id = auth.uid());
create policy "authenticated read records" on public.sample_records for select to authenticated using (true);
create policy "authenticated add records" on public.sample_records for insert to authenticated with check (true);
create policy "authenticated edit records" on public.sample_records for update to authenticated using (true) with check (true);
create policy "admin delete records" on public.sample_records for delete to authenticated using (public.is_admin());

-- Histórico de lançamentos diários. A base permanece em sample_records e não é
-- repetida aqui: cada lançamento representa somente a produção daquela data.
create table if not exists public.daily_records (
  id bigint generated by default as identity primary key,
  coordinator text not null default '',
  leader text not null default '',
  record_date date not null,
  confirmed integer not null default 0 check (confirmed >= 0),
  not_confirmed integer not null default 0 check (not_confirmed >= 0),
  does_not_know integer not null default 0 check (does_not_know >= 0),
  mailbox integer not null default 0 check (mailbox >= 0),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.daily_records enable row level security;
create policy "authenticated read daily records" on public.daily_records for select to authenticated using (true);
create policy "authenticated add daily records" on public.daily_records for insert to authenticated with check (true);
create policy "authenticated edit daily records" on public.daily_records for update to authenticated using (true) with check (true);
create policy "admin delete daily records" on public.daily_records for delete to authenticated using (public.is_admin());

insert into public.sample_records (coordinator, leader, total_base, confirmed, not_confirmed, does_not_know, mailbox)
select * from (values
 ('Carlos Eduardo','Gisele Martins',50,15,0,0,2), ('Carlos Eduardo','Aline Santos',20,6,0,1,1),
 ('Mariana Costa','Jackson Rodrigues',395,50,30,5,10), ('Mariana Costa','Jhon Cleber',16,4,0,0,1),
 ('Roberto Alves','Josinei Graça',209,50,12,3,5), ('Roberto Alves','Meirian Arruda',206,47,14,2,8),
 ('Carlos Eduardo','Saulo Mesquita',13,3,0,0,0)
) as rows(coordinator, leader, total_base, confirmed, not_confirmed, does_not_know, mailbox)
where not exists (select 1 from public.sample_records);

-- Depois de criar as contas em Authentication > Users, execute uma vez:
-- update public.profiles set role = 'admin', display_name = 'Admin' where id = (select id from auth.users where email = 'admin@amostragem.app');
